apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prune-pipelineruns
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - list
      - delete
